# Generated by Django 4.1.1 on 2022-10-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erabiltzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('pasahitza', models.CharField(max_length=30)),
                ('mota', models.IntegerField(choices=[(0, 'Admin'), (1, 'Bezeroa'), (2, 'Banatzailea')])),
            ],
        ),
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=255)),
                ('deskribapena', models.CharField(max_length=255)),
                ('prezioa', models.FloatField()),
                ('stock', models.FloatField()),
                ('mota', models.IntegerField(choices=[(0, 'Osagaia'), (1, 'Platera'), (2, 'Edaria')])),
            ],
        ),
        migrations.CreateModel(
            name='Eskaera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('egoera', models.IntegerField(choices=[(0, 'Karrito'), (1, 'Bidean'), (2, 'Faktura')])),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.erabiltzailea')),
            ],
        ),
    ]
