# Generated by Django 4.1.1 on 2022-10-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EskaeraLerroa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kopurua', models.IntegerField()),
                ('eskaera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.eskaera')),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produktua')),
            ],
        ),
    ]
