# Generated by Django 4.1.1 on 2022-11-03 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_eskaeralerroa'),
    ]

    operations = [
        migrations.AddField(
            model_name='erabiltzailea',
            name='erabitlzailea_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
