# Generated by Django 4.1.1 on 2022-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_erabiltzailea_erabitlzailea_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabiltzailea',
            name='mota',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Bezeroa'), (2, 'Banatzailea')], default=1),
        ),
    ]
