# Generated by Django 3.1.4 on 2022-11-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20221103_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktua',
            name='foto',
            field=models.CharField(default='null.jpg', max_length=255),
        ),
    ]
