# Generated by Django 4.1.1 on 2022-11-03 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_produktua_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='email',
        ),
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='pasahitza',
        ),
        migrations.AddField(
            model_name='erabiltzailea',
            name='erabitlzailea_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='erabiltzailea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='erabiltzailea',
            name='mota',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Bezeroa'), (2, 'Banatzailea')], default=1),
        ),
        migrations.AlterField(
            model_name='eskaera',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eskaeralerroa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produktua',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
