# Generated by Django 4.1.1 on 2022-11-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_erabiltzailea_mota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='email',
        ),
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='pasahitza',
        ),
    ]
