# Generated by Django 3.1.4 on 2022-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20221115_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='erabiltzailea',
            name='ordainketaMota',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
